fragment MoneyFields on MoneyV2 {
  amount
  currencyCode
}

fragment AddressFields on CustomerAddress {
  id
  firstName
  lastName
  company
  address1
  address2
  city
  province
  zoneCode
  country
  territoryCode
  zip
  phoneNumber
}

query GetCustomer {
  customer {
    id
    emailAddress {
      emailAddress
      marketingState
    }
    firstName
    lastName
    phoneNumber {
      phoneNumber
    }
    defaultAddress {
      ...AddressFields
    }
  }
}

mutation CustomerUpdate($input: CustomerUpdateInput!) {
  customerUpdate(input: $input) {
    customer {
      id
      emailAddress {
        emailAddress
        marketingState
      }
      firstName
      lastName
      phoneNumber {
        phoneNumber
      }
      defaultAddress {
        ...AddressFields
      }
    }
    userErrors {
      field
      message
      code
    }
  }
}
