app = 'nakedpineapple-log-shipper'
primary_region = 'sjc'

[build]
  dockerfile = 'log-shipper/Dockerfile'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[services]]
  http_checks = []
  internal_port = 8686
