//! Auto-generated image manifest for content-based hashing.
//!
//! DO NOT EDIT - Generated by scripts/image-optimizer/optimize-images.mjs

use std::collections::HashMap;
use std::sync::LazyLock;

/// Maps image base paths to their content hashes.
///
/// Key: base path without extension (e.g., `"lifestyle/DSC_1068"`)
/// Value: 8-character content hash
pub static IMAGE_HASHES: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    HashMap::from([
        (
            "products/naked-pineapple-vip-bundle/NP_-_Photoshoot_2148",
            "49c4b90f",
        ),
        ("lifestyle/DSC_1068", "c30a5102"),
        (
            "about/DSC_5841_7937b270-76ec-46ca-94be-0d898b03767f",
            "ae33eb2d",
        ),
        ("model-program/Model_Program_Feb_2025_160", "3bc9c7e2"),
        (
            "products/pineapple-enzyme-cleanser/Model_Program_March_2025_38",
            "03c307ab",
        ),
        ("model-program/Model_Program_March_2025_7", "01ee4da7"),
        (
            "products/pineapple-facial-oil/Model_Program_March_2025_19",
            "06579ea4",
        ),
        (
            "products/naked-pineapple-vip-bundle/Model_Program_March_2025_39",
            "2b2a16f6",
        ),
        ("model-program/Model_Program_Feb_2025_22", "f2af06ac"),
        (
            "products/glow-up-bronzing-facial-oil/Model_Program_March_2025_53",
            "66770f89",
        ),
        (
            "products/skin-tight-exotic-cream/Model_Program_March_2025_44",
            "ebd7c8a7",
        ),
        ("model-program/Model_Program_March_2025_41", "0ffc8fce"),
        (
            "products/pineapple-enzyme-cleanser/Model_Program_March_2025_16",
            "b7b882ab",
        ),
        (
            "products/naked-pineapple-vip-bundle/Model_Program_Feb_2025_7",
            "d0c6dc42",
        ),
        ("model-program/Model_Program_Feb_2025_65", "d03dccd4"),
        (
            "products/starter-kit/Model_Program_March_2025_14_536fbe04-c22c-496b-837e-4f1ed60c0717",
            "367f8dad",
        ),
        ("products/naked-pineapple-vip-bundle/DSC_7695", "bb615259"),
        ("merch/hoodie/DSC_5849", "ebaceb61"),
        ("lifestyle/DSC_2634", "9748b64b"),
        ("products/pineapple-facial-oil/DSC_7750", "60df071e"),
        ("lifestyle/DSC_6128", "1eca42bf"),
        ("lifestyle/NP_Shoot_-_Jan_202579", "e98e71fc"),
        ("merch/other/DSC_6659", "568040b5"),
        ("lifestyle/374FA1B1-5C0E-442A-83E5-892DB550D7F5", "d4203684"),
        ("lifestyle/NP_-_Photoshoot_1156", "f388ac20"),
        ("lifestyle/BBFEF851-7EC3-4A07-A1ED-EF9A15CEA821", "efad37f3"),
        ("merch/other/NP_Shoot_-_Jan_2025133", "0c3c68a1"),
        ("lifestyle/DSC_1594", "eb58b794"),
        ("merch/other/NP_Shoot_-_Jan_202547", "75cdb9f2"),
        ("merch/display/Merch_Photos", "07faeb0a"),
        (
            "merch/other/10_18172443-bd3f-416a-b2fa-6726ca776c28",
            "4313f65c",
        ),
        ("lifestyle/NP_Shoot_-_Jan_2025101", "60dcefe9"),
        ("testimonials/Maddie_-_Before_NP2", "d1adff33"),
        ("testimonials/Maddie_-_After_NP", "b4d71633"),
        (
            "products/pineapple-enzyme-cleanser/NP_-_Photoshoot_268",
            "dc7b9bed",
        ),
        ("lifestyle/NP_-_Photoshoot_186", "6dc7c821"),
        (
            "products/pineapple-enzyme-cleanser/NP_-_Photoshoot_262",
            "efcc5832",
        ),
        (
            "products/naked-pineapple-vip-bundle/NP_-_Photoshoot_2128",
            "47f26bc5",
        ),
        ("events/launch-party/Launch_Party_-_NP498", "5fecdf65"),
        (
            "products/bright-tight-super-serum/NP_-_Photoshoot_278",
            "11ebcf60",
        ),
        (
            "products/skin-tight-exotic-cream/NP_-_Photoshoot_280",
            "5370aa9a",
        ),
        (
            "merch/dad-hat/042F576F-1C53-4B61-9B30-10D53B5EBE79",
            "8b888190",
        ),
        (
            "events/launch-party/IMG_4106_d384f118-38d8-46a4-b92a-9174ba3d357f",
            "f612a03c",
        ),
        (
            "products/pineapple-facial-oil/NP_-_Photoshoot_238",
            "4e321aba",
        ),
        ("payment/visa", "1ef276a5"),
        ("payment/mastercard", "910f266e"),
        ("payment/amex", "d89ad285"),
        ("payment/apple-pay", "8720a7d6"),
        ("payment/google-pay", "71a6aee7"),
        ("payment/shop-pay", "b7cf386c"),
        ("branding/Logo_Horizontal", "71cba526"),
        ("branding/Pistachio_MarkOnly", "a8e348cf"),
        ("hero/hero-self-love", "38d1eb7b"),
        ("hero/hero-glow-better", "43943eba"),
        ("hero/hero-tennis", "41b4d7c0"),
        ("hero/hero-pickleball", "d9dacc28"),
        ("hero/hero-holding-product", "28127b3b"),
    ])
});

/// Look up the content hash for an image path.
///
/// Returns the hash if found, or an empty string if not found.
#[must_use]
pub fn get_image_hash(base_path: &str) -> &'static str {
    IMAGE_HASHES.get(base_path).copied().unwrap_or("")
}

/// Look up the maximum generated width for an image path.
///
/// Returns the max width if found, or 0 if not found.
/// SVGs return 0 (they are resolution-independent).
///
/// NOTE: This is a placeholder that returns 2400 for all images.
/// The actual values will be generated by the image optimizer.
#[must_use]
pub const fn get_image_max_width(_base_path: &str) -> u32 {
    // TODO: This will be replaced by the image optimizer with actual values
    // For now, return 2400 to include all sizes (existing behavior)
    2400
}
